// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTIx5q789QokGHPPsCbzW5xUxI03B3hLU',
    appId: '1:717697979750:web:42393114d4db5420d924a7',
    messagingSenderId: '717697979750',
    projectId: 'sapura-42b81',
    authDomain: 'sapura-42b81.firebaseapp.com',
    storageBucket: 'sapura-42b81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqogw2jhLFZ8I3YI7151OK0V99O4eegio',
    appId: '1:717697979750:android:cfc5249fedb171d3d924a7',
    messagingSenderId: '717697979750',
    projectId: 'sapura-42b81',
    storageBucket: 'sapura-42b81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoyh0p-P3U8d8RSBmZ_3zyFlpnmy7cSBE',
    appId: '1:717697979750:ios:52ba4062757022e0d924a7',
    messagingSenderId: '717697979750',
    projectId: 'sapura-42b81',
    storageBucket: 'sapura-42b81.appspot.com',
    iosBundleId: 'com.mjd.sapuratm.sapuraTm',
  );
}
